Lets start angular#2
KajetanKisielewski/video-app-angular pull request #2
Opened 2023-03-21 08:49 UTC by KajetanKisielewski

2023-03-21 10:31 UTC, GrzegorzDryja requested changes

2023-03-21 10:31 UTC, GrzegorzDryja commented on video-app-angular/src/app/core/services/http.service.ts
> +    return this.http.get<VimeoVideo>( path, { headers } ).pipe(
Pipe tu nie jest potrzebny. Do wstrzykiwania headerów fajnie użyć interceptora.

2023-03-21 10:31 UTC, GrzegorzDryja commented on video-app-angular/src/app/core/services/video.service.ts
> +    if(recognizedUrlProvider === UrlProvider.YouTube) return this.addYouTubeVideo(url);
W sumie nawet spoko się to czyta, jednak stworzyłeś funkcję typu void a zwracasz dwie różne funkcje i alert.

2023-03-21 18:49 UTC, bronasek requested changes

2023-03-21 18:49 UTC, bronasek commented on video-app-angular/src/app/core/module/material.module.ts
> +  imports: [...materialModules],
cos nie tak ze wcieciami tu jest

2023-03-21 18:49 UTC, bronasek commented on video-app-angular/src/app/core/services/local-storage.service.ts
> +  private storageKey: string = 'videos'
przy prostej zmiennej jak juz masz przypisaną wartość to nie trzeba pisac typu - ts sam wie

2023-03-21 18:49 UTC, bronasek commented on video-app-angular/src/app/home/video-list/video-item/video-item.component.html
> +<mat-card class="item">
mozna byłoby się pokusić o barrdziej opisową nazwę klasy

2023-03-22 13:06 UTC, KajetanKisielewski commented on video-app-angular/src/app/core/services/http.service.ts
> +    return this.http.get<VimeoVideo>( path, { headers } ).pipe(
Co do pipe, to potrzebuję zwrócić tu również id, stąd te zastosowanie.

2023-03-22 13:08 UTC, KajetanKisielewski commented on video-app-angular/src/app/core/services/video.service.ts
> +    if(recognizedUrlProvider === UrlProvider.YouTube) return this.addYouTubeVideo(url);
Obie te funkcję zwracają `void`, alert również, więc w ostatecznym rozrachunku ta funkcja również zwraca `void`

2023-03-22 14:24 UTC, GrzegorzDryja approved these changes

2023-03-22 14:24 UTC, GrzegorzDryja commented on video-app-angular/src/app/home/search-bar/search-bar.component.ts
>    public inputFieldValue: string = '';
Przy inicjalizacji typ zaleca się pominąć.

2023-03-22 14:24 UTC, GrzegorzDryja commented on video-app-angular/src/app/home/video-list/video-list.component.html
> +<div *ngIf="videos$ | async as videos" class="video__container">
To zostaje tak jak, tu czy porzucasz ngIf?

2023-03-22 15:11 UTC, bronasek approved these changes

2023-04-03 00:52 UTC, merged